export const allOrders = [
  {
    _id: 1,
    orderTime: "3-10-2022",
    productName: "Hp Core",
    phone: "1233333",
    paymentMethod: "paypal",
    orderAmount: 333,
    status: "pending",
  },
  {
    _id: 2,
    orderTime: "6-10-2022",
    productName: "Camera",
    phone: "43443",
    paymentMethod: "stripe",
    orderAmount: 3211,
    status: "delivered",
  },
  {
    _id: 3,
    orderTime: "22-9-2022",
    productName: "Monitor",
    phone: "123242",
    paymentMethod: "card",
    orderAmount: 3211,
    status: "pending",
  },
  {
    _id: 4,
    orderTime: "1-7-2022",
    productName: "Camera",
    phone: "49695",
    paymentMethod: "stripe",
    orderAmount: 3211,
    status: "processing",
  },
  {
    _id: 5,
    orderTime: "7-1-2022",
    productName: "Monitor",
    phone: "8978",
    paymentMethod: "paypal",
    orderAmount: 3211,
    status: "pending",
  },
  {
    _id: 6,
    orderTime: "7-1-2022",
    productName: "Monitor",
    phone: "8978",
    paymentMethod: "paypal",
    orderAmount: 3211,
    status: "pending",
  },
  {
    _id: 7,
    orderTime: "7-1-2022",
    productName: "Monitor",
    phone: "8978",
    paymentMethod: "paypal",
    orderAmount: 3211,
    status: "pending",
  },
];
