export const allOrders = [
  {
    _id: 1,
    orderTime: "3-10-2022",
    productName: "Hp Core",
    phone: "1233333",
    paymentMethod: "paypal",
    orderAmount: 333,
    status: "pending",
  },
  {
    _id: 2,
    orderTime: "6-10-2022",
    productName: "Camera",
    phone: "43443",
    paymentMethod: "stripe",
    orderAmount: 3211,
    status: "delivered",
  },
  {
    _id: 3,
    orderTime: "22-9-2022",
    productName: "Monitor",
    phone: "123242",
    paymentMethod: "card",
    orderAmount: 3211,
    status: "pending",
  },
  {
    _id: 4,
    orderTime: "1-7-2022",
    productName: "Camera",
    phone: "49695",
    paymentMethod: "stripe",
    orderAmount: 3211,
    status: "processing",
  },
  {
    _id: 5,
    orderTime: "7-1-2022",
    productName: "Monitor",
    phone: "8978",
    paymentMethod: "paypal",
    orderAmount: 3211,
    status: "pending",
  },
  {
    _id: 6,
    orderTime: "7-1-2022",
    productName: "Monitor",
    phone: "8978",
    paymentMethod: "paypal",
    orderAmount: 3211,
    status: "pending",
  },
  {
    _id: 7,
    orderTime: "7-1-2022",
    productName: "Monitor",
    phone: "8978",
    paymentMethod: "paypal",
    orderAmount: 3211,
    status: "pending",
  },
  {
    _id: 8,
    orderTime: "8-1-2022",
    productName: "Monitor",
    phone: "8978",
    paymentMethod: "paypal",
    orderAmount: 3211,
    status: "processing",
  },
  {
    _id: 9,
    orderTime: "7-2-2022",
    productName: "Monitor",
    phone: "8978",
    paymentMethod: "paypal",
    orderAmount: 3211,
    status: "pending",
  },
  {
    _id: 10,
    orderTime: "7-11-2022",
    productName: "Monitor",
    phone: "8978",
    paymentMethod: "paypal",
    orderAmount: 3211,
    status: "processing",
  },
  {
    _id: 11,
    orderTime: "3-1-2022",
    productName: "Monitor",
    phone: "8978",
    paymentMethod: "paypal",
    orderAmount: 3211,
    status: "pending",
  },
  {
    _id: 12,
    orderTime: "17-1-2022",
    productName: "Monitor",
    phone: "8978",
    paymentMethod: "paypal",
    orderAmount: 3211,
    status: "delivered",
  },
  {
    _id: 13,
    orderTime: "7-10-2022",
    productName: "Monitor",
    phone: "8978",
    paymentMethod: "paypal",
    orderAmount: 3211,
    status: "pending",
  },
  {
    _id: 14,
    orderTime: "7-6-2022",
    productName: "Monitor",
    phone: "8978",
    paymentMethod: "paypal",
    orderAmount: 3211,
    status: "pending",
  },
  {
    _id: 15,
    orderTime: "17-5-2022",
    productName: "Monitor",
    phone: "8978",
    paymentMethod: "paypal",
    orderAmount: 3211,
    status: "delivered",
  },
  {
    _id: 16,
    orderTime: "17-10-2022",
    productName: "Monitor",
    phone: "8978",
    paymentMethod: "paypal",
    orderAmount: 3211,
    status: "processing",
  },
];
